health:
 check:
  message: This is THE test message from Config Server
  port: local.server.port

db:
 url: jdbc:h2:mem:testdb
 driver: org.h2.Driver
 username: sa
 password:
 
actuator:
 url: /actuator/health

sentencePrefix: Sentence = 
